---

- name: Set deprecated services
  systemd:
    name: "networking"
    enable: "{{ not(vars['systemd_networkd::disable_deprecated'] | default (true)) }}"
    mask: "{{ vars['systemd_networkd::disable_deprecated'] | default (true) }}"

- name: Set systemd-network
  systemd:
    name: "systemd-networkd"
    enable: "{{ vars['systemd_networkd::enable'] | default(true) }}"
    mask: "{{ not(vars['systemd_networkd::enable'] | default(true)) }}"
