---

- name: Set deprecated services
  systemd:
    name: "networking"
    enabled: "{{ not(vars['systemd_networkd::disable_deprecated'] | default (true)) }}"
    masked: "{{ vars['systemd_networkd::disable_deprecated'] | default (true) }}"

- name: Set systemd-network
  systemd:
    name: "systemd-networkd"
    enabled: "{{ vars['systemd_networkd::enable'] | default(true) }}"
    masked: {{ not(vars['systemd_networkd::enable']) | default(true)) }}
