---

- name: Set deprecated services
  systemd:
    name: "networking"
    enable: "{{ not(systemd_networkd::disable_deprecated | default (true)) }}"
    mask: "{{ systemd_networkd::disable_deprecated | default (true) }}"

- name: Set systemd-network
  systemd:
    name: "systemd-networkd"
    enable: "{{ systemd_networkd::enable | default(true) }}"
    mask: "{{ not(systemd_networkd::enable | default(true)) }}"
